let allMusic = [
  {
    name: "Vardaan",
    artist: "CarryMinati X Wily Frenzy",
    img: "vardaan",
    src: "Vardaan",
  },
  {
    name: "Yalgaar",
    artist: "CarryMinati X Wily Frenzy",
    img: "yalgaar",
    src: "Yalgaar",
  },
  {
    name: "Trigger",
    artist: "Carryminati - Trigger",
    img: "trigger",
    src: "Trigger",
  },
  {
    name: "Shrivalli",
    artist: "T Series",
    img: "shrivalli",
    src: "Shrivalli",
  },
  {
    name: "Stay",
    artist: "Justin Bieber",
    img: "stay",
    src: "Stay",
  },
  {
    name: "Astronaut In The Ocean",
    artist: "Masked Wolf",
    img: "astronaut-in-the-ocean",
    src: "Astronaut-in-the-ocean",
  },
  {
    name: "Believer",
    artist: "Imagine Dragons",
    img: "believer",
    src: "Believer",
  },
  {
    name: "Unstoppable",
    artist: "Sia",
    img: "unstoppable",
    src: "Unstoppable",
  },
  {
    name: "Cradles",
    artist: "Sub Urban",
    img: "cradles",
    src: "Cradles",
  },
  {
    name: "No Lie",
    artist: "Sean Paul, Dua Lipa",
    img: "no-lie",
    src: "No-Lie",
  },
  {
    name: "On My Way",
    artist: "Alan Walker, Sabrina Carpenter",
    img: "on-my-way",
    src: "On-My-Way",
  },
  {
    name: "Levitating",
    artist: "Dua Lipa",
    img: "levitating",
    src: "Levitating",
  },
  {
    name: "Falak Tak Chal Sath Mere",
    artist: "Udit Narayan",
    img: "falak-tak",
    src: "Falak-Tak",
  },
  {
    name: "Pasoori x Habibi",
    artist: "Ali Sethi x Shae Gill ",
    img: "pasoori",
    src: "Pasoori",
  },
  {
    name: "One Kiss x I Was Never There",
    artist: "Dua Lipa x Calvin Harris",
    img: "one-kiss",
    src: "One-Kiss",
  },

  {
    name: "Tum Mere",
    artist: "Fukra Insaan X CrazyDeep",
    img: "tum-mere",
    src: "Tum-Mere",
  },
  {
    name: "Tu Aake Dekh Le",
    artist: "King",
    img: "tu-aake-dekh-le",
    src: "Tu-Aake-Dekh-Le",
  },
  {
    name: "Dancin",
    artist: "Aaron Smith",
    img: "dancin",
    src: "Dancin",
  },
  {
    name: "Bones",
    artist: "Imagin Dragons",
    img: "bones",
    src: "Bones",
  },
  {
    name: "Enemy",
    artist: "Imagine Dragons",
    img: "enemy",
    src: "Enemy",
  },
  {
    name: "Middle of the Night",
    artist: "Elley Duhe",
    img: "middle-of-the-night",
    src: "Middle-Of-The-Night",
  },
  {
    name: "Infinity",
    artist: "Jaymes Young",
    img: "infinity",
    src: "Infinity",
  },
  {
    name: "One Dance",
    artist: "Drake",
    img: "one-dance",
    src: "One-Dance",
  },
  {
    name: "Heat Waves",
    artist: "Glass Animals",
    img: "heat-waves",
    src: "Heat-Waves",
  },
  {
    name: "Stereo Hearts",
    artist: "Gym Class Heroes",
    img: "stereo-hearts",
    src: "Stereo-Hearts",
  },
];
